[build]
  publish = "public"
  command = "echo Build OK"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
    Service-Worker-Allowed = "/"
