name: bufferwave_app_pro
description: BufferWave - Réseau Coopératif DTN
publish_to: 'none'
version: 4.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.0
  web_socket_channel: ^3.0.3
  http: ^1.2.0
  flutter_svg: ^2.0.0
  shimmer: ^3.0.0
  lottie: ^3.0.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.3
  geolocator: ^11.0.0
  permission_handler: ^11.0.0
  google_mobile_ads: ^5.1.0
  cryptography: ^2.7.0
  flutter_secure_storage: ^9.0.0
  fl_chart: ^0.69.0
  share_plus: ^9.0.0
  pointycastle: ^4.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true